### ISSUE TITLE
Active States on Some Links Broken

### ISSUE THREAD

**Issue by mason-at-pieces** [pieces-app/news#18]
# Overview

When clicking on the 2023 `Microsoft Teams App` button, it doesn't highlight the link when it is selected. When you the click the other pages, they become highlighted when you are on that page but it is broken for this specific link.

<img width="1806" alt="Screenshot 2023-06-24 at 12 09 27 PM" src="https://github.com/pieces-app/news/assets/123421085/bcc9af48-b6e5-4aec-98da-9b82875c6b47">

## List of broken links:
- [Microsoft Build 2023](https://news.pieces.app/#Microsoft%20Build%202023)
- [Microsoft Teams App](https://news.pieces.app/#Pieces%20for%20Developers%20Microsoft%20Teams%20App%20Available%20on%20Teams%20Store!)
- [Chromium Browser Extension](https://news.pieces.app/#Pieces%20Helps%20Developers%20Save%20&%20Organize%20Code%20Snippets%20Directly%20from%20the%20Browser%20with%20Chromium%20Browser%20Extension)
- [JetBrains Plugin Released](https://news.pieces.app/#Pieces%20for%20JetBrains%20released)
- [VSCode Extension Released](https://news.pieces.app/#Pieces%20for%20VS%20Code:%20Productivity%20Enhancements%20Directly%20in%20your%20IDE)

**Comment by jwafu** [comment]
thanks mason - in the future be sure to assign these to me so i can get them updated when they are created ! :)
