### ISSUE TITLE
News Events Updates

### ISSUE THREAD

**Issue by georgia-at-pieces** [pieces-app/news#19]
- [x] VS Code hit 20,000 Installs
- [x] Launch on Product Hunt
- [x] InfoShare

https://docs.google.com/document/d/1iEWMTgwSoQz29aNc2WBLD_NrseIsz5RYqzqdhFofZBY/edit

**Comment by georgia-at-pieces** [comment]
@connor-ohearn-at-pieces could you review/add to the doc above when you get a chance?

**Comment by connor-ohearn-at-pieces** [comment]
Made some adjustments. Thanks!

**Comment by jwafu** [comment]
will get this updated !! be sure to tag or assign things to someone when we want to get them slotted to be completed. Otherwise there are no notifications sent out
