### ISSUE TITLE
News Updates

### ISSUE THREAD

**Issue by connor-ohearn-at-pieces** [pieces-app/news#26]
Howdy, what am I missing here? 
https://docs.google.com/document/d/1gDEHHLXgQI5P6aOBa_3m6tFCqPtHMx3U4IWP0-GEdmI/edit?usp=sharing

**Comment by jwafu** [comment]
I would just get some images in there if you can @connor-ohearn-at-pieces otherwise it is looking pretty good

**Comment by connor-ohearn-at-pieces** [comment]
Are there other events we should highlight?

**Comment by jwafu** [comment]
### Events
- software engineering daily 
	- https://softwareengineeringdaily.com/2023/10/25/building-pieces-app-and-the-future-of-developer-productivity-with-tsavo-knott/
		- October 25th 2023
- dzone fireside chats
	- https://dzone.com/events/video-library/Increasing-Dev-Performance-KPIs-AI-and-Bottlenecks
		- november 1nd, 2023
- hanselminutes redefining developer workflow 
	- https://www.hanselminutes.com/913/redefining-developer-workflow-with-piecesapps-tsavo-knott
		- october 5th, 2023
- emerj podcast
	- https://podcast.emerj.com/solving-software-developer-challenges-with-ai-with-tsavo-knott-of-pieces
		- october 26th 2023
- pieces story livestream with google 
	- https://www.youtube.com/watch?v=rPVbDGbnWzw
	- https://cloudonair.withgoogle.com/events/building-with-ai-pieces-livestream?mkt_tok=ODA4LUdKVy0zMTQAAAGPbb-2Vmcze4_9GrMKT5WNLTp3nkd5yXiVXP2FF7tph-oaln_k0OyjM3goMEonng88SY1mNy2jKWrqD88gSERxcUG5AjVBQ_CR6wi7zQpAwfQxpofYT58 
		- november 14th, 2023

**Comment by jwafu** [comment]
@connor-ohearn-at-pieces these are all of the events/podcast things that i could find ^^

**Comment by jwafu** [comment]
there may be more but it seems like the only person who knows is tsavos calendar lol

**Comment by connor-ohearn-at-pieces** [comment]
Roger that, thanks man, I will make some more stories and add in some pics 
Thank you!

**Comment by connor-ohearn-at-pieces** [comment]
Erin is adding in some images and then I think we will be good to go

**Comment by connor-ohearn-at-pieces** [comment]
Beware of dates order @jordan-pieces

**Comment by connor-ohearn-at-pieces** [comment]
Here is the latest, take a pass... I think we are pretty good to go. Not sure if there are any more images 

https://docs.google.com/document/d/1gDEHHLXgQI5P6aOBa_3m6tFCqPtHMx3U4IWP0-GEdmI/edit?usp=sharing

**Comment by georgia-at-pieces** [comment]
Looking good to me!

**Comment by jwafu** [comment]
@connor-ohearn-at-pieces absolutely killer this is looking great! 🔥 ill start working on these soon

**Comment by connor-ohearn-at-pieces** [comment]
@jordan-pieces i have 1 more SOC 2 update for you!

date can be 

November 22, 2023

H1: Pieces for Developers Achieves SOC 2 Compliance

Exciting news! We've achieved SOC 2 compliance, marking a significant milestone for our team. SOC 2 compliance is a testament to our commitment to the highest standards of security and operational practices.

SOC 2 is a prestigious benchmark in the tech industry, especially important for companies like ours. It verifies that we meet strict organizational controls and practices, enhancing our credibility and trustworthiness in the market.

This achievement is a collective triumph for our team, reflecting our dedication to maintaining a secure and reliable service. It's an essential step forward in our mission to provide word class developer tools.

**Comment by jwafu** [comment]
I was wondering how this issue opened back up haha ill take care of this ! @connor-ohearn-at-pieces
