### ISSUE TITLE
Spice up the Sidebar, add more events + other upgrades 

### ISSUE THREAD

**Issue by jwafu** [pieces-app/news#28]
Few things would love to updated: 

- [ ] add emojis to sidebar headers 
- [ ] update the buttons throughout and their styling 

Any other updates to the news site as a whole to make it feel more alive would be ideal - but we will see what else we can get added into here.

**Comment by UtkarshUmre** [comment]
hey @jordan-pieces I would like to work on this issue. Can you assign this to me?

**Comment by jwafu** [comment]
@UtkarshUmre apologies for my slow response on this issue as we are just returning from the winter holiday break. before we get into the code, why don't we work through a few things and if you can answer these questions that would be great before starting to write: 

- [ ] 1. add a list with each of the headers and the corresponding emoji that you would like to use there from [emojipedia](emojipedia) in the comments on this issue 

  **example:**
  ![Screenshot 2024-01-03 at 5 48 22 PM](https://github.com/pieces-app/news/assets/55861512/64d14bdc-7168-4843-9c88-f2da4bbda7dd)

- [ ] 2. find a button (or submit a design as a screenshot to show what you are thinking for the buttons throughout the news site

**Comment by jwafu** [comment]
hey @UtkarshUmre - have not heard any updates here and just wanted to check in 👍
